const {chromium}=require(process.env.JAQ_PLAYWRIGHT_PATH || 'playwright');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({...(process.env.JAQ_BROWSER_EXECUTABLE?{executablePath:process.env.JAQ_BROWSER_EXECUTABLE}:{}),headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1100},timezoneId:'America/Sao_Paulo'});
 const page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.JAQ_TEST_URL || 'http://127.0.0.1:5188');
 await page.getByLabel('Usuário',{exact:true}).fill('dona.teste');
 await page.getByLabel('Senha',{exact:true}).fill('Jaq.Teste.2026!');
 await page.getByRole('button',{name:'Entrar',exact:true}).click();
 await page.getByRole('button',{name:'Serviços',exact:true}).waitFor();
 await page.getByRole('button',{name:'Serviços',exact:true}).click();
 await page.getByLabel('Buscar serviço').fill('mega');
 if(await page.locator('[data-service-search]:visible').count()<5)throw Error('Service search failed');
 await page.getByRole('button',{name:'Clientes',exact:true}).click();
 await page.getByRole('button',{name:'＋ Nova cliente',exact:true}).click();
 await page.getByLabel('Nome da cliente',{exact:true}).fill('Cliente da prévia');
 await page.getByLabel('Telefone / WhatsApp').fill('11987654321');
 await page.getByLabel('Objetivo da cliente').fill('Loiro iluminado, com acompanhamento de manutenção.');
 await page.getByRole('button',{name:'Salvar',exact:true}).click();
 await page.getByRole('heading',{name:'Cliente da prévia',exact:true}).waitFor();
 await page.getByRole('button',{name:'Nova comanda',exact:true}).click();
 await page.getByRole('button',{name:'Salvar',exact:true}).click();
 await page.getByRole('button',{name:'＋ Adicionar serviço',exact:true}).waitFor();
 const add=async(service,staff,start,minutes)=>{
  await page.getByRole('button',{name:'＋ Adicionar serviço',exact:true}).click();
  await page.getByLabel('Serviço',{exact:true}).selectOption({label:service});
  await page.getByLabel('Responsável',{exact:true}).selectOption({label:staff});
  await page.getByLabel('Início (horário de Brasília)').fill(start);
  await page.getByLabel('Duração (minutos)').fill(String(minutes));
  await page.getByRole('button',{name:'Salvar',exact:true}).click();
  await page.locator('#modal').waitFor({state:'hidden'});
 };
 await add('Mechas cabelo todo — longo','Atendente 01','2031-10-06T09:00',180);
 await add('Hidratação','Atendente 02','2031-10-06T09:00',30);
 await add('Escova Joico — lisa ou modelada','Atendente 02','2031-10-06T09:30',30);
 await page.getByText('R$ 1.730,00',{exact:true}).first().waitFor();
 await page.screenshot({path:require('node:path').join(process.env.JAQ_TEST_SCREENSHOT_DIR || 'work','jaq-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'Registrar recebimento',exact:true}).click();
 await page.getByLabel('Valor recebido (R$)').fill('300');
 await page.getByLabel('Tipo',{exact:true}).selectOption('deposit');
 await page.getByRole('button',{name:'Salvar',exact:true}).click();
 await page.locator('#modal').waitFor({state:'hidden'});
 await page.getByText('R$ 1.430,00',{exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile horizontal overflow');
 await page.screenshot({path:require('node:path').join(process.env.JAQ_TEST_SCREENSHOT_DIR || 'work','jaq-mobile.png'),fullPage:true});
 await page.getByRole('button',{name:'Equipe',exact:true}).click();
 await page.getByRole('button',{name:'＋ Adicionar atendente',exact:true}).click();
 await page.getByLabel('Nome',{exact:true}).fill('Atendente teste interface');
 await page.getByRole('button',{name:'Salvar',exact:true}).click();
 await page.locator('#modal').waitFor({state:'hidden'});
 const row=page.locator('.list-row').filter({hasText:'Atendente teste interface'});
 await row.getByRole('button',{name:'Editar',exact:true}).click();
 await page.getByLabel('Ativa no salão').uncheck();
 await page.getByRole('button',{name:'Salvar',exact:true}).click();
 await page.locator('#modal').waitFor({state:'hidden'});
 await row.getByText('Inativa',{exact:true}).waitFor();
 if(errors.length)throw Error(errors.join('\n'));
 fs.writeFileSync(process.env.JAQ_BROWSER_RESULTS || 'work/browser-results.json',JSON.stringify({passed:true,checks:['Login','Busca de serviços','Cadastro de cliente com ficha técnica','Comanda com três serviços e duas atendentes','Sinal abatido do saldo','Gestão de equipe e desativação','Layout móvel sem rolagem horizontal','Sem erros JavaScript']},null,2));
 await browser.close();console.log('PASS: fluxo de interface completo em desktop e celular.');
})().catch(e=>{console.error(e);process.exit(1)});
